### ISSUE TITLE
Add iframe based transport for web wallets

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#223]
**Summary**
Web Wallets currently use the p2p transport. They could potentially instead use an iframe based transport so communication happens locally.

**Describe the expected behaviour**
The iframe based approach should behave similar to the PostMessage transport.

**Proof of Concept**

A proof of concept of the bridge is available here:

https://airgap-it.github.io/beacon-iframe-bridge/example.html

https://github.com/airgap-it/beacon-iframe-bridge

Currently, the following browsers are tested with the iframe bridge:

| Browser | Desktop | iOS | Android | 
|---------|---------|-----|---------|
| Chrome  |  ✅  |     |         |  
| Firefox |     |     |         |  
| Safari  |  ✅ |     |         |  
| Brave   |   ✅ |     |         |  
| Opera   |         |     |         |  

**Todo**

- [ ] Test browser compatibility (Mobile? Incognito?)
- [ ] Define how the connection is established (deeplink, or through the iframe?)
- [ ] Security implications of using an iframe instead of P2P
- [ ] Add iframe transport to beacon-sdk, or make postMessage transport compatible with the iframe based approach
- [ ] Fallback to p2p in case bridge doesn't work
